version: "3"

volumes:
  postgre_data:

networks:
  postgre_network:
    driver: bridge
  nginx_network:
    driver: bridge

services:
  api:
    build: 
      context: api
      dockerfile: ./docker/prod/Dockerfile
    env_file:
      - ./.env.prod
    restart: always
    networks:
      - postgre_network
      - nginx_network
    depends_on:
      - db
  db:
    image: postgres:11.4-alpine
    restart: always
    volumes:
      - postgre_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
    networks:
      - postgre_network
  front:
    build:
      context: front
      dockerfile: ./docker/prod/Dockerfile
    env_file:
     - ./.env.prod
    networks:
      - nginx_network
  nginx:
    image: nginx:1.17.2-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3001:80
    networks:
      - nginx_network
    depends_on:
      - api
      - front
