# Generated by Django 3.0.5 on 2020-11-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(verbose_name='image')),
                ('banner_type', models.CharField(choices=[('combo', 'Combo'), ('web_view', 'Web View'), ('product', 'Product'), ('info', 'Info')], max_length=10, verbose_name='banner_type')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
    ]
