# Generated by Django 3.0.5 on 2020-11-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20201114_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('combo', 'Combo'), ('web_view', 'Web View'), ('product', 'Product'), ('info', 'Info')], max_length=10, verbose_name='banner_type'),
        ),
    ]
